#!/usr/bin/env python3
"""Push the AI-generated Strategy section to a RHAISTRAT issue in Jira.

Reads the existing Jira description (preserving human-authored content),
then appends or replaces the "## Strategy (AI Generated by Agentic SDLC
Pipeline)" section with the locally refined version.

Usage:
    python3 scripts/push_strategy.py RHAISTRAT-1520 artifacts/strat-tasks/RHAISTRAT-1520.md

Environment variables:
    JIRA_SERVER  Jira server URL
    JIRA_USER    Jira username/email
    JIRA_TOKEN   Jira API token
"""

import argparse
import re
import sys

from jira_utils import (
    require_env,
    get_issue,
    adf_to_markdown,
    markdown_to_adf,
    api_call_with_retry,
    strip_metadata,
)


STRATEGY_HEADING = "## Strategy (AI Generated by Agentic SDLC Pipeline)"
STAFF_INPUT_HEADING = "## Staff Engineer Input"
STAFF_INPUT_TEMPLATE = """## Staff Engineer Input
<!-- HIGH-PRIORITY: Content here is used as primary guidance during strategy refinement. -->
<!-- Add technical corrections, architectural direction, component preferences, or domain expertise. -->
<!-- Write it using declarative, cumulative form; policy and statement that shall always be valid in any iteration of the STRAT Refinement -->
<!-- This input takes priority over architecture context and removed-context when they conflict. -->
<!-- After review: address findings below, then remove the needs_attention label from Jira. -->"""


def extract_strategy_section(local_content):
    """Extract the Strategy section from a local strategy file."""
    match = re.search(
        r'(## Strategy \(AI Generated by Agentic SDLC Pipeline\).*?)(?=\n## (?!#)|$)',
        local_content,
        re.DOTALL,
    )
    if not match:
        return None
    return match.group(1).strip()


def update_description(server, user, token, issue_key, description_adf):
    """PUT only the description field (no summary change)."""
    body = {"fields": {"description": description_adf}}
    path = f"/issue/{issue_key}"
    api_call_with_retry(server, path, user, token, body=body, method="PUT")


def main():
    parser = argparse.ArgumentParser(description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("issue_key", help="RHAISTRAT issue key")
    parser.add_argument("local_file", help="Local strategy file path")
    args = parser.parse_args()

    server, user, token = require_env()
    if not all([server, user, token]):
        print("Error: JIRA_SERVER, JIRA_USER, and JIRA_TOKEN required.",
              file=sys.stderr)
        sys.exit(2)

    with open(args.local_file, "r", encoding="utf-8") as f:
        local_content = f.read()

    local_content = strip_metadata(local_content)

    strategy_section = extract_strategy_section(local_content)
    if not strategy_section:
        print("Error: no Strategy section found in local file.",
              file=sys.stderr)
        sys.exit(1)

    issue = get_issue(server, user, token, args.issue_key,
                      fields=["description"])
    existing_desc = issue.get("fields", {}).get("description")
    existing_md = adf_to_markdown(existing_desc).strip() if existing_desc else ""

    if STRATEGY_HEADING in existing_md:
        updated_md = re.sub(
            r'## Strategy \(AI Generated by Agentic SDLC Pipeline\).*?(?=\n## (?!#)|$)',
            strategy_section + "\n",
            existing_md,
            flags=re.DOTALL,
        )
    else:
        updated_md = existing_md + "\n\n" + strategy_section

    if STAFF_INPUT_HEADING not in updated_md:
        updated_md = updated_md.rstrip() + "\n\n" + STAFF_INPUT_TEMPLATE

    updated_adf = markdown_to_adf(updated_md)
    update_description(server, user, token, args.issue_key, updated_adf)
    print(f"OK: Strategy section pushed to {args.issue_key}")


if __name__ == "__main__":
    main()
